zappyproject/zappyapp/urls.py
from zappyapp import views
from django.urls import path
from django.conf import settings


app_name='zappyapp'
urlpatterns = [
    path('', views.home,name='home'),
    path('registration',views.registration,name='registration'),
    path('updateprofile',views.cprofile,name='uprofile'),
    path('profile',views.profile,name='profile'),
    path('details/<id>',views.productsdetails),
    path('search',views.search,name='search'),
    path('ReadyToeat', views.readytoeat,name='readytoeat'),
    path('ReadyToCook', views.readytocook,name='readytocook'),
    path('addtocart',views.addtocart,name='addtocart'),
    path('cartview',views.cart_view,name='cartview'),
    path('cartitems',views.cartitems,name='cartitems'),
    path('cartupdates',views.cartupdates,name='cartupdates'),
    path('cartdel',views.cartdel,name='cartdel'),
    path('checkout',views.checkout,name='checkout'),
    path('orderhistory',views.orderh,name='orderhistory'),
    ]

zappyproject/zappyproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('zappyapp.urls')),
    path('login',auth_views.LoginView.as_view(template_name='zappyapp/login.html'),name='login'),
    path('logout',auth_views.LogoutView.as_view(template_name='zappyapp/logout.html'),name='logout'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

zappyproject/zappyapp/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image


class Product(models.Model):
    categories=(('rte','Ready To Eat'),('rtc','Ready To Cook'))
    cat_choice=models.CharField(max_length=20,choices=categories,default='rte')
    pname=models.CharField(max_length=200)
    image=models.ImageField(upload_to='Products',default='Products/1-1.jpg')
    description=models.TextField()
    price=models.IntegerField()

    def __str__(self):
        return self.pname


class Customer(models.Model):
    customer=models.OneToOneField(User,on_delete=models.CASCADE)
    cust_address=models.CharField(max_length=400,default=None,null=True,blank=True)
    mobile = models.CharField(max_length=12)
    images = models.ImageField(upload_to='Customers',default='Customers/default.jpg')

    def __str__(self):
        return self.mobile


class Order(models.Model):
    users=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    pids=models.TextField(null=True)
    delievery_address=models.CharField(max_length=200)
    status=models.IntegerField(default=0)

zappyproject/zappyapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Customer,Order


class CustomerUpdate(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['images','cust_address','mobile',]


class Checkout(forms.ModelForm):
    delievery_address=forms.CharField(required=False)
    class Meta:
        model=Order
        widgets = {'delievery_address': forms.TextInput(attrs={'placeholder': 'Same as Billing Address'})}
        fields=['delievery_address']

zappyproject/zappyapp/views.py
from django.shortcuts import render,reverse,redirect
from django.contrib.auth.forms import UserCreationForm
from zappyapp.models import Product,Customer,Order
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from zappyapp.forms import CustomerUpdate,Checkout
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger



def home(request):
    productes=Product.objects.all().order_by('-id') # Query to get all Product in decreasing order by id
    page = request.GET.get('page', 1)
    paginator = Paginator(productes, 6)
    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        products = paginator.page(1)
    except EmptyPage:
        products = paginator.page(paginator.num_pages)
    return render(request,'zappyapp/home.html',{'products': products})

def readytoeat(request):
    products=Product.objects.filter(cat_choice='rte').order_by('-id') # Query to get all Product in readytoeat category in decreasing order by id
    return render(request,'zappyapp/rte.html',{'products':products})

def readytocook(request):
    products=Product.objects.filter(cat_choice='rtc').order_by('-id') # Query to get all Product in readytoeat category in decreasing order by id
    return render(request,'zappyapp/rtc.html',{'products':products})

def productsdetails(request,id):
    products=Product.objects.get(id=id) # Query to get a Single Product in all products using an id
    return render(request,'zappyapp/productdetails.html',{'products':products})

def registration(request):
    reg_form=UserCreationForm(request.POST or None)
    if reg_form.is_valid():
        reg_form.save()
        return HttpResponseRedirect(reverse('zappyapp:home'))
    return render(request,'zappyapp/registration.html',{'reg_form':reg_form})

def search(request):
    query=request.GET.get('q')
    productes=Product.objects.filter(pname__icontains=query) # Search Query to search products using their Name
    if productes is not None:
        page = request.GET.get('page', 1)
        paginator = Paginator(productes, 6)
        try:
            products = paginator.page(page)
        except PageNotAnInteger:
            products = paginator.page(1)
        except EmptyPage:
            products = paginator.page(paginator.num_pages)
        return render(request,'zappyapp/home.html',{'products':products})
    else:
        return HttpResponseRedirect(reverse('zappyapp:home'))

# Cart CRUD Views Started

def addtocart(request):
    response=HttpResponseRedirect(reverse('zappyapp:cartitems'))
    id=request.GET.get('product_id')
    item=request.GET.get('items')
    print(dir(request.COOKIES))
    print(request.COOKIES.items())
    if id in request.COOKIES.keys():
        items=int(request.COOKIES.get(id))
        item=int(item)+items
        response.set_cookie(id,item)
    else:
        response.set_cookie(id,item)
    return response


def cart_view(request):
    products=Product.objects.all()
    price, img, pname = [], [], []
    for i,j in request.COOKIES.items():
        if i.isdigit() and j.isdigit():
            img.append(Product.objects.get(id=i).image.url)
            pname.append(Product.objects.get(id=i).pname)
            price.append(Product.objects.get(id=i).price*int(j))
    total=sum(price)
    dict={'price':price,'total':total,'img':img,'pname':pname}
    if not request.COOKIES.items():
        price, img, pname, total = [], [], [], 0
    return render(request,'zappyapp/cartview.html',context=dict)


def cartitems(request):
    length=0
    for i,j in request.COOKIES.items():
        if i.isdigit() and j.isdigit():
            length+=1
    response=updations(request)
    response.set_cookie('length',length)
    return response


def cartupdates(request):
    response=updations(request)
    id=request.GET.get('product_id')
    item=request.GET.get('items')
    if id in request.COOKIES.keys():
        response.set_cookie(id,item)
    return response


def updations(request):
    return HttpResponseRedirect(reverse('zappyapp:cartview'))


def cartdel(request):
    response=HttpResponseRedirect(reverse('zappyapp:cartitems'))
    id=request.GET.get('product_id')
    if id in request.COOKIES.keys():
        response.delete_cookie(id)
    return response

# Cart CRUD Ended

# login Required View Started
@login_required
def orderh(request):
    order=Order.objects.filter(users=request.user).order_by('-id')
    return render(request, 'zappyapp/orderhistory.html',{'order':order})


@login_required
def profile(request):
    return render(request, 'zappyapp/profile.html')


@login_required
def cprofile(request):
    if request.method == 'POST':
        cu_form = CustomerUpdate(request.POST,request.FILES,instance=request.user.customer)
        if cu_form.is_valid():
            cu_form.save()
            return HttpResponseRedirect(reverse('zappyapp:profile'))
    else:
        cu_form = CustomerUpdate(request.POST,request.FILES,instance=request.user.customer)
    return render(request, 'zappyapp/cprofile.html',{'cu_form':cu_form})

@login_required
def checkout(request):
    products=[]
    add=Customer.objects.get(customer=request.user).cust_address
    for i,j in request.COOKIES.items():
        if i.isdigit() and j.isdigit():
            products.append(Product.objects.get(id=i).pname)
    if request.method == 'POST':
        ch_form = Checkout(request.POST)
        if ch_form.is_valid():
            test=ch_form.save(commit=False)
            if len(test.delievery_address):
                pass
            else:
                if add is None:
                    return HttpResponseRedirect(reverse('zappyapp:uprofile'))
                else:
                    test.delievery_address=add
            test.users=request.user
            test.pids=products
            test.save()
            response=render(request,'zappyapp/sucess.html')
            for i in request.COOKIES.keys():
                if i.isdigit() or i=='length':
                    response.delete_cookie(i)
            return response
    else:
        ch_form = Checkout()
    return render(request, 'zappyapp/checkout.html',{'ch_form':ch_form})
# Login Required Views Ended

zappyproject/templates/zappyapp/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Custom JS -->
    <script src="{%static "js/jquery-3.3.1.min.js"%}" ></script>
    <script src="{%static "js/infinite.js"%}" ></script>
    <script src="{%static "js/bootstrap.js"%}" ></script>
    <link href="{%static "favicon/favicon.ico"%}" rel="shortcut icon" type="image/vnd.microsoft.icon" />
    {%block refresh%}
    {%endblock refresh%}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Zappy Foods</title>
    <!-- FontAwesome core CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Custom styles for this template -->
    <link href="{% static "css/bootstrap.css" %}" rel="stylesheet">
    <link href="{% static "css/home.css" %}" rel="stylesheet">
    <link href="{% static "css/sticky-footer.css" %}" rel="stylesheet">
  </head>
  <body>
    <header>
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo03" aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <a class="navbar-brand" href="{%url 'zappyapp:home'%}">Zappy Foods</a>
      <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
        <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
          <li class="nav-item active">
            <a class="nav-link" href="{%url 'zappyapp:home'%}">Home <span class="sr-only">(current)</span></a>
          </li>
          {% if user.is_authenticated is False%}
          <li class="nav-item">
            <a class="nav-link" href="{%url 'zappyapp:registration'%}">Registration</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{%url 'login'%}">Log In</a>
          </li>
          {%endif%}
          {% if user.is_authenticated is True%}
          <li class="nav-item">
            <a class="nav-link " href="{%url 'logout' %}">Log Out</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{%url 'zappyapp:profile' %}">My Account</a>
          </li>
          <li class="nav-item">
            <a class="nav-link " href="{%url 'zappyapp:orderhistory' %}">Order History</a>
          </li>
          {%endif%}
          <li class="nav-item">
            <a class="nav-link " href="{%url 'zappyapp:cartview'%}"><i class="fa fa-shopping-cart fa-2x">{%if request.COOKIES.length != '0'%}{{request.COOKIES.length}}{%endif%}</i></a>
          </li>
        </ul>
        <form class="form-inline my-2 my-lg-0" action="{% url 'zappyapp:search' %}" method="GET">
          <input class="form-control mr-sm-2" type="search" placeholder="Search..." name="q" value="{{request.GET.q}}" aria-label="Search">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
        </form>
      </div>
    </nav>
    </header>
      {%block cartview%}
      {%endblock cartview%}
    <main role="main">
        {%block products%}
        {%endblock products%}
    </main>
    {%block account%}
    {%endblock account%}
    {%block footer%}
    {%endblock footer%}
  </body>
</html>

zappyproject/templates/zappyapp/cart.html
{%extends 'zappyapp/base.html'%}
{%block products%}
<div class="album py-5 bg-light">
  <div class="container">
<h1>Cart</h1>
{%if val%}
{%for i in val%}
<h4>{{i}}</h4>
{%endfor%}
{%endif%}
</div>
</div>
{%endblock products%}

zappyproject/templates/zappyapp/cartview.html
{%extends 'zappyapp/base.html'%}
{%block cartview%}
<div class="container">
  {%if price%}
  <div class="row">
    <div class="col-md-3">
      <table class="table">
        <thead>
          <tr>
          <th scope="col">Image</th>
        </tr>
        </thead>
        <tbody>
          {%for i in img%}
          <tr>
            <td><img src="{{i}}" height="25" width="45" alt=""></td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>
    <div class="col-md-3">
      <table class="table table-md">
        <thead>
          <tr>
          <th scope="col">Product Name</th>
        </tr>
        </thead>
        <tbody>
          {%for i in pname%}
          <tr>
            <td>{{i}}</td>
          </tr>
          {%endfor%}
        </tbody>
      </table>
    </div>
<div class="col-md-4">
<table class="table">
  <thead>
    <tr>
      <!-- <th scope="col">product_id</th> -->
      <th scope="col">Quantity</th>
    </tr>
  </thead>
  <tbody>
    {%for key,value in request.COOKIES.items%}
    {%if key.isdigit%}
    <tr>
      <td>
      <form method="GET" action="{%url 'zappyapp:cartupdates'%}" >
      <input type="hidden" name="product_id" value="{{key}}"/>
      <input class="text-center control-sm"  min="1" max="50" type="number" name="items" value="{{value}}"/>
      </form>
      </td>
      <td>
      <form method="GET" action="{%url 'zappyapp:cartdel'%}" class="form-group"> <button name="product_id" value="{{key}}" type="submit"  class="btn btn btn-outline-secondary btn-sm">Remove</button></form>
      </td>
    </tr>
    {%endif%}
    {%endfor%}
  </tbody>
</table>
</div>
<div class="col-md-2">
<table class="table">
    <thead>
      <tr>
        <th scope="col">Price</th>
      </tr>
    </thead>
    <tbody>
      {%for p in price%}
      <tr>
        <td>{{p}}</td>
      </tr>
      {%endfor%}
      {%if price%}
      <tr>
        <td>Total={{total}}</td>
      </tr>
      {%endif%}
    </tbody>
</table>
</div>
</div>
{%else%}
<div class="jumbotron">
  <h1 class="display-4">You Dont Added Any Products</h1>
  <p class="lead">This is a simple hero unit, a simple jumbotron-style component for calling extra attention to featured content or information.</p>
  <hr class="my-4">
  <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
  <p class="lead">
    <a class="btn btn-primary btn-lg" href="{%url 'zappyapp:home'%}" role="button">Add Something</a>
  </p>
</div>
{%endif%}
{%if price%}
<form method="GET" action="{%url 'zappyapp:checkout'%}" class="form-group float-md-right"> <button name="" value="" type="submit"  class="btn btn btn-outline-secondary btn-sm">Checkout</button></form>
{%endif%}
</div>
{%endblock cartview%}

zappyproject/templates/zappyapp/checkout.html
{%extends 'zappyapp/base.html'%}
{%load crispy_forms_tags%}

{%block products%}

<div class="container">
  <br><br><br>
    <div class="content-section" >
  <form method="post">
    {%csrf_token%}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Delievery Details </legend>
      <input type="checkbox" onchange="myFunction()" name="" value="Address Is Same As Billing Address"/>&nbsp Address Is Same As Billing Address
      <br>
        {{ch_form|crispy}}
    </fieldset>
<div class="form-group">
  <button type="submit" class="btn btn-outline-info">Save</button>
</div>
  </form>
</div>
</div>
<script type="text/javascript">
function myFunction() {
  var x = document.getElementById("div_id_delievery_address");
  var y = document.getElementById("id_delievery_address");
  if (x.style.display === "none") {
      x.style.display = "block";
      y.value='';
  } else {
      x.style.display = "none";
  }

}
</script>
{%endblock products%}

zappyproject/templates/zappyapp/home.html
{%extends 'zappyapp/base.html'%}
{%block products%}
{%if products%}
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Welcome to the
World of Zappy</h1>
    <p class="lead text-muted">Where life is full of happiness
Or as we say ‘Zappyness’</p>
    <p>
      <a href="{% url 'zappyapp:readytoeat'%}"  class="btn btn-primary my-2">Ready To Eat Foods</a>
      <a href="{% url 'zappyapp:readytocook'%}" class="btn btn-secondary my-2">Ready To Cook Foods</a>
    </p>
  </div>
</section>


<div class="album py-5 bg-light">
  <div class="container">
<h1>Latest items</h1>
<hr>
    <div class="row">
      {%for i in products%}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <a href="details/{{i.id}}"><img class="card-img-top" height="225" src="{{i.image.url}}" alt="Card image cap"></a>
          <div class="card-body">
            <p class="card-text">{{i.pname}}</p>
            <div class="d-flex justify-content-between align-items-center">
              <form class="form-group" action="{%url 'zappyapp:addtocart'%}" method="GET">
                <!-- {% csrf_token %} -->
              <div class="btn-group">
                <input type="hidden" name="product_id" value="{{i.id}}">
                <input type="hidden" name="product_price" value="{{i.price}}">
                <button type="submit"  class="btn btn btn-outline-secondary btn-sm">Add to Cart</button>&nbsp&nbsp
                <input type="number" class="text-center" name="items" value="1" min="1" max="50" step="1">
                <!-- <button type="button" class="btn btn btn-outline-secondary btn-sm">Add to Wishlist</button> -->
              </div>
              </form>
              <h5 class="text-muted"><i class="fa fa-rupee">{{i.price}}</i></h5>
            </div>
          </div>
        </div>
      </div>

      {%endfor%}
      <br>


    </div>
    <div class="col-md-2">
      {% if products.has_next %}
      <button class="view-more-button btn btn-primary">View more</button>
      {% endif %}
    </div>

    {% if products.has_next %}
    <a class="pagination__next" href="?page={{ products.next_page_number }}"></a>
  {% endif %}
  </div>
</div>
{%else%}
<div class="album py-5 bg-light" id="nop">
  <div class="container text-center">
<h1>Sorry But No Products Matching</h1>

</div>
</div>
{%endif%}
<script type="text/javascript">
$(".row").infiniteScroll({
// options
path: ".pagination__next",
append: ".col-md-4",
history: false,
button: '.view-more-button',
// load pages on button click
scrollThreshold: false,
// disable loading on scroll
});
</script>

<script type="text/javascript">
$(document).ready(function(){
	$("#id_product").blur(function(){
		var pname=$("#id_product").val();
    console.log(pname);
	   alert(pname);
  $.ajax({
			url:'checkproduct',
      data: {
        'pname': pname
          },
			type:'get',
      dataType: 'json',
      success: function (data) {
        if (data.is_taken) {
          alert("Product already exists.");
          $("#id_product").val("");
                           }
      });
    });
});
</script>
{%endblock products%}

{%block footer%}
{%if products%}
<footer class="footer">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <div class="copy-footer container-fluid text-center">Copyright &reg; 2015 Zappyfoods.in All rights reserved.</div>
  </div>
</footer>
{%endif%}
{%endblock footer%}

zappyproject/templates/zappyapp/login.html
{%extends 'zappyapp/base.html'%}
{%load crispy_forms_tags%}
{%block account%}
<div class="container">
<br><br><br>
    <div class="content-section" >
      <legend class="border-bottom mb-4">Login</legend>
      <form method="post">
        {%csrf_token%}
        <fieldset class="form-group">

            {{form|crispy}}
        </fieldset>
    <div class="form-group">
      <button type="submit" class="btn btn-outline-info">Login</button>
    </div>
      </form>
</div>
  <br>
  Don't Have Account? <a href="{%url 'zappyapp:registration'%}">Create Here</a>
</div>
{%endblock account%}

{%block footer%}

<footer class="footer">
  <div class="container">
    <div class="copy-footer container-fluid text-center">Copyright &reg; 2015 Zappyfoods.in All rights reserved.</div>
  </div>
</footer>

{%endblock footer%}

zappyproject/templates/zappyapp/productdetails.html
{%extends 'zappyapp/base.html'%}
{%block products%}
<div class="container">
      <div class="row">
        <div class="col-md-12 blog-main">
          <div class="blog-post">
            <br><br>
            <h1 class="blog-post-title">{{products.pname}}</h1>
            <hr>
          </div>
           <img class="img-fluid" src="{{products.image.url}}" alt="">
           <hr>

          <div class="d-flex justify-content-between align-items-center">
            <form class="form-group" action="{%url 'zappyapp:addtocart'%}" method="POST">
              {% csrf_token %}
            <div class="btn-group">
              <input type="hidden" name="product_id" value="{{products.id}}">
              <input type="hidden" name="product_price" value="{{products.price}}">
              <button type="submit"  class="btn btn btn-outline-secondary btn-sm">Add to Cart</button>&nbsp&nbsp
              <input type="number" class="text-center" name="items" value="1" min="1" max="20" step="1">&nbsp&nbsp&nbsp&nbsp
              <button type="button" class="btn btn btn-outline-secondary btn-sm"><i class="fa fa-rupee">{{products.price}}</i></button>
              <!-- <button type="button" class="btn btn btn-outline-secondary btn-sm">Add to Wishlist</button> -->
            </div>
            </form>
          </div>
        <hr>
        <p class="blog-post-title">{{products.description}}</p>
        </div>
      </div>
    </div>


{%endblock products%}

zappyproject/templates/zappyapp/profile.html
{%extends 'zappyapp/base.html'%}
{%load crispy_forms_tags%}
{%block products%}
<br><br>
<main role="main" class="container">
<div class="row">
        <div class="col-md-8">
          <div class="card" style="width: 50%;">
            <img class="card-img-top" src="{{ user.customer.images.url }}" alt="Card image cap">
            <div class="card-body">
              <h3 class="card-title">{{ user.username }}</h3>
              <p class="card-text">{{ user.customer.mobile }}</p>
              <p class="card-text">{{ user.customer.cust_address }}</p>
              <a href="{%url 'zappyapp:uprofile'%}" class="btn btn-primary">Update Profile</a>
            </div>
          </div>

  </div>

  <div class="col-md-4">

       </div>
</div>
</main>
{%endblock products%}

zappyproject/templates/zappyapp/rtc.html
{%extends 'zappyapp/base.html'%}
{%block products%}
{%if products%}
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Welcome to the
World of Zappy</h1>
    <p class="lead text-muted">Where life is full of happiness
Or as we say ‘Zappyness’</p>
    <p>
      <a href="{% url 'zappyapp:readytoeat'%}" class="btn btn-primary my-2">Ready To Eat Foods</a>
    </p>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container">
<h1>Latest items</h1>
<hr>
    <div class="row">
      {%for i in products%}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <a href="details/{{i.id}}"><img class="card-img-top" height="225" src="{{i.image.url}}" alt="Card image cap"></a>
          <div class="card-body">
            <p class="card-text">{{i.pname}}</p>
            <div class="d-flex justify-content-between align-items-center">
              <form class="form-group" action="{%url 'zappyapp:addtocart'%}" method="GET">

              <div class="btn-group">
                <input type="hidden" name="product_id" value="{{i.id}}">
                <input type="hidden" name="product_price" value="{{i.price}}">
                <button type="submit"  class="btn btn btn-outline-secondary btn-sm">Add to Cart</button>&nbsp&nbsp
                <input type="number" class="text-center" name="items" value="1" min="1" max="20" step="1">
                <!-- <button type="button" class="btn btn btn-outline-secondary btn-sm">Add to Wishlist</button> -->
              </div>
              </form>
              <h5 class="text-muted"><i class="fa fa-rupee">{{i.price}}</i></h5>
            </div>
          </div>
        </div>
      </div>
      {%endfor%}
    </div>
  </div>
</div>
{%else%}
<div class="album py-5 bg-light" id="nop">
  <div class="container text-center">
<h1>No Products To Display</h1>
</div>
</div>
{%endif%}
{%endblock products%}
{%block footer%}
{%if products%}
<footer class="footer">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <div class="copy-footer container-fluid text-center">Copyright &reg; 2015 Zappyfoods.in All rights reserved.</div>
  </div>
</footer>
{%endif%}
{%endblock footer%}

zappyproject/templates/zappyapp/rte.html
{%extends 'zappyapp/base.html'%}
{%block products%}
{%if products%}
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Welcome to the
World of Zappy</h1>
    <p class="lead text-muted">Where life is full of happiness
Or as we say ‘Zappyness’</p>
    <p>
      <a href="{% url 'zappyapp:readytocook'%}" class="btn btn-secondary my-2">Ready To Cook Foods</a>
    </p>
  </div>
</section>
<div class="album py-5 bg-light">
  <div class="container">
<h1>Latest items</h1>
<hr>
    <div class="row">
      {%for i in products%}
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <a href="details/{{i.id}}"><img class="card-img-top" height="225" src="{{i.image.url}}" alt="Card image cap"></a>
          <div class="card-body">
            <p class="card-text">{{i.pname}}</p>
            <div class="d-flex justify-content-between align-items-center">
              <form class="form-group" action="{%url 'zappyapp:addtocart'%}" method="GET">
              <div class="btn-group">
                <input type="hidden" name="product_id" value="{{i.id}}">
                <input type="hidden" name="product_price" value="{{i.price}}">
                <button type="submit"  class="btn btn btn-outline-secondary btn-sm">Add to Cart</button>&nbsp&nbsp
                <input type="number" class="text-center" name="items" value="1" min="1" max="20" step="1">
                <!-- <button type="button" class="btn btn btn-outline-secondary btn-sm">Add to Wishlist</button> -->
              </div>
              </form>
              <h5 class="text-muted"><i class="fa fa-rupee">{{i.price}}</i></h5>
            </div>
          </div>
        </div>
      </div>
      {%endfor%}
    </div>
  </div>
</div>
{%else%}
<div class="album py-5 bg-light" id="nop">
  <div class="container text-center">
<h1>No Products To Display</h1>
</div>
</div>
{%endif%}
{%endblock products%}
{%block footer%}
{%if products%}
<footer class="footer">
  <div class="container">
    <p class="float-right">
      <a href="#">Back to top</a>
    </p>
    <div class="copy-footer container-fluid text-center">Copyright &reg; 2015 Zappyfoods.in All rights reserved.</div>
  </div>
</footer>
{%endif%}
{%endblock footer%}